### ISSUE TITLE
d3.simple.chart.css

### ISSUE THREAD

**Issue by moverserg** [MaximPetrichuk/d3.simple.chart#2]
Add file, please!

**Comment by MaximPetrichuk** [comment]
What file?

**Comment by moverserg** [comment]
d3.simple.chart.css

**Comment by moverserg** [comment]
In index.html
`<link rel="stylesheet" href="d3.simple.chart.css">`
If it is needed...

**Comment by MaximPetrichuk** [comment]
Sorry, I added it to index.html and forgot to remove link.

**Comment by moverserg** [comment]
Ok! =) Sorry
